services:
  mysql-wakanda-transporte-movilidad:
    image: mysql:8.0
    hostname: mysql-wakanda-transporte-movilidad
    environment:
      - MYSQL_DATABASE=Backend-Wakanda-Transporte-Movilidad
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - "3321:3306"
    networks:
      - backend-network
    healthcheck: # Comprueba si MySQL está listo antes de aceptar conexiones
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3306", "-u", "root", "-pP@ssw0rd" ]
      interval: 10s
      retries: 5
      timeout: 5s

  backend_wakanda_agua:
    build:
      context: ./
    container_name: backend_wakanda_transporte_movilidad
    ports:
      - "8087:8097"
    networks:
      - backend-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=default
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-wakanda-transporte-movilidad:3306/Backend-Wakanda-Transporte-Movilidad?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
    depends_on:
      mysql-wakanda-transporte-movilidad:
        condition: service_healthy  # Espera a que MySQL esté "healthy"
    entrypoint:
      [
        "./wait-for-it.sh", "eureka-server:8761", "-t", "60", "--",
        "./wait-for-it.sh", "mysql-wakanda-transporte-movilidad:3306", "-t", "60", "--",
        "java", "-jar", "/app/backend-wakanda-transporte-movilidad.jar",
      ]

volumes:
  mysql-data:

networks:
  backend-network:
    external: true
