spring:

  datasource:
    url: jdbc:mysql://mysql-wakanda-transporte-movilidad:3306/Backend-Wakanda-Transporte-Movilidad?serverTimezone=UTC
    username: root
    password: P@ssw0rd

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  application:
    name: backend_wakanda_transporte_movilidad

server:
  port: 8097

jwt:
  secret: securesecretkey


error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.myproyect.springboot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

metrics:
  export:
    prometheus:
      enabled: true
