@startuml
left to right direction

actor Usuario as U

package "Sistema Transporte y Movilidad" {

    usecase "Consultar Información de Transporte" as CI
    usecase "Visualizar Detalles de Transporte" as VT
    usecase "Obtener Rutas de Transporte" as RT
    usecase "Solicitar Datos de Transporte Específico" as ST

    rectangle "TransporteFactory" {
        usecase "Crear Datos de Transporte" as CT
    }

    CI --> VT : Detalles
    CI --> RT : Rutas
    VT --> ST : Solicita Datos
    ST --> CT : Crea Datos

    U --> CI
    U --> VT
    U --> RT
}
@enduml
